image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start
    command: zsh

  - name: Start
    command: |
      [ -d /workspace/djangorm ] || mkdir -p /workspace/djangorm && \
      cd /workspace/djangorm && \
      curl -sL https://github.com/petronny/djangorm/archive/refs/heads/master.tar.gz | tar zxvf - --strip-components=1
